"""empty message

Revision ID: 2527eb269670
Revises: 14e09e961b94
Create Date: 2026-01-07 10:39:04.193648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2527eb269670'
down_revision = '14e09e961b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('card_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_message', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('message')

    # ### end Alembic commands ###
