"""empty message

Revision ID: 63512d0cf297
Revises: 8517fa8bd922
Create Date: 2026-01-02 10:20:32.863880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63512d0cf297'
down_revision = '8517fa8bd922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
