"""empty message

Revision ID: 8517fa8bd922
Revises: 082563b71245
Create Date: 2026-01-02 10:01:25.554508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8517fa8bd922'
down_revision = '082563b71245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_message', sa.String(), nullable=False))
        batch_op.drop_column('card_messsage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_messsage', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('card_message')

    # ### end Alembic commands ###
